# PARCOMINE CONFIG FILE

temp: /tmp
permanentDir: /data/bitextor/permanent/bitextor-output
transientDir: /data/bitextor/transient
dataDir: /data/bitextor/data

moses: /root/mosesdecoder
mgiza: /root/mgiza
bicleaner: /root/bicleaner
zipporah: /root/zipporah
hunalign: /root/hunalign

wordTokenizers: {
    default: /root/mosesdecoder/scripts/tokenizer/tokenizer.perl -q -b -a -l en,
    en: /root/mosesdecoder/scripts/tokenizer/tokenizer.perl -q -b -a -l en,
    ja: mecab -Owakati 
}

sentenceSplitters: {
    default: /root/mosesdecoder/scripts/ems/support/split-sentences.perl -q -b -l en,
    en: /root/mosesdecoder/scripts/ems/support/split-sentences.perl -q -b -l en,
    ja: /root/mosesdecoder/scripts/ems/support/split-sentences.perl -q -b -l ja,
}

lang1: en
lang2: ja

#hosts: ["yotsutake.co.jp"]
#hosts: ["ahatoro.com"]
hosts: ["akisuzuki.com"]

task: [
    "concat",
    "preprocessing",
    "align-document",
    "align-paragraph",
    "align-sentence",
    "filtering",
]

crawler: heritrix

ftfy: true

cleanHTML: true

boilerpipeCleaning: false

pdf-converter: "pdf-extract"

parser: bs4

neologdn: true

langId: cld2

documentAligner: URL

paragraphAligner: STRAND

sentenceAligner: HUNALIGN
#sentenceAligner: LASER

filter: BICLEANER
#filter: ZIPPORAH

laser_model_dir: /root/LASER/models
laser_encoder: /root/LASER/models/bilstm.93langs.2018-12-26.pt
laser_bpe_codes: /root/LASER/models/93langs.fcodes
laser_threshold: 1.1
laser_enc_gpu: false
laser_knn_gpu: false

hunalignDic: /data/bitextor/model/hunalign/en-ja/hunalign.en-ja.dic
hunalignThreshold: 0.0

bicleanerConfig: /data/bitextor/model/bicleaner/en-ja/bicleaner.en-ja.yaml
bicleanerThreshold: 0.4

#zipporahDir: "/data/bitextor/model/zipporah"
#zipporahConfig: "/data/bitextor/model/zipporah/config"
#zipporahModel: "/data/bitextor/model/zipporah/en-ja.model"
#zipporahDic1: "/data/bitextor/model/zipporah/dict.en-ja"
#zipporahDic2: "/data/bitextor/model/zipporah/dict.ja-en"
#zipporahVocab1: "/data/bitextor/model/zipporah/vocab.en"
#zipporahVocab2: "/data/bitextor/model/zipporah/vocab.ja"
#zipporahLM1: "/data/bitextor/model/zipporah/lm.en"
#zipporahLM2: "/data/bitextor/model/zipporah/lm.ja"
#zipporahThreshold: 0.0

bifixer: false

elrc: false

tmx: true

deduped: true
