# PARCOMINE CONFIG FILE

temp: /tmp
permanentDir: /data/bitextor/permanent/bitextor-output
transientDir: /data/bitextor/transient
dataDir: /data/bitextor/data

wordTokenizers: {
    en: /root/preprocess/moses/tokenizer/tokenizer.perl -q -b -a -l en,
    ja: mecab -Owakati 
}

sentenceSplitters: {
    en: /root/preprocess/moses/ems/support/split-sentences.perl -q -b -l en,
    ja: /root/preprocess/moses/ems/support/split-sentences.perl -q -b -l yue,
}

lang1: en
lang2: ja

crawler: heritrix
heritrixPath: /root/heritrix-3.4.0-SNAPSHOT
heritrixUrl: https://localhost:8443
heritrixUser: admin:admin
heritrixContactUs: https://paracrawl.eu/ 

hosts: ["www.totoku.co.jp", "www.totoku.com"]

#onlyConcat: true 
onlyPreprocessing: true

disableFTFY: false

cleanHTML: false

boilerpipeCleaning: false

pdf-converter: "pdf-extract"

langId: cld2

dic: /data/bitextor/dic_data/en-ja.dic
initCorpusTrainPrefix: [
    "/data/bitextor/dic_data/GlobalVoices/GlobalVoices.en-jp",
    "/data/bitextor/dic_data/OpenSubtitles/OpenSubtitles.en-ja",
    "/data/bitextor/dic_data/Tatoeba/Tatoeba.en-ja",
]

#documentAligner: DIC
documentAligner: URL

hunalignThreshold: 0.0

bicleaner: /data/bitextor/bicleaner-model/en-ja/training.en-ja.yaml
bicleanerThreshold: 0.4
bicleanerCorpusTrainingPrefix: [
    "/data/bitextor/dic_data/GlobalVoices/GlobalVoices.en-jp",
    "/data/bitextor/dic_data/OpenSubtitles/OpenSubtitles.en-ja",
    "/data/bitextor/dic_data/Tatoeba/Tatoeba.en-ja",
]

bifixer: false

elrc: false

tmx: true

deduped: true
