# PARCOMINE CONFIG FILE

temp: /tmp
permanentDir: /data/bitextor/permanent/bitextor-output
transientDir: /data/bitextor/transient
dataDir: /data/bitextor/data

moses: /root/mosesdecoder
mgiza: /root/mgiza
bicleaner: /root/bicleaner
zipporah: /root/zipporah
hunalign: /root/hunalign

wordTokenizers: {
    default: /root/mosesdecoder/scripts/tokenizer/tokenizer.perl -q -b -a -l en,
    en: /root/mosesdecoder/scripts/tokenizer/tokenizer.perl -q -b -a -l en,
    ja: mecab -Owakati 
}

sentenceSplitters: {
    default: /root/abc/scripts/pragmatic_segmenter.rb en,
    en: /root/abc/scripts/pragmatic_segmenter.rb en,
    ja: /root/abc/scripts/pragmatic_segmenter.rb ja,
}

lang1: en
lang2: ja

#hosts: ["ahatoro.com", "yotsutake.co.jp"]
#hosts: ["ahatoro.com"]
#hosts: ["yotsutake.co.jp"]
#hosts: ["www.asiabiomass.jp"]
#hosts: ["akisuzuki.com"]
#hosts: ["www.accorhotels.com"]
#hosts: ["takagi-j.com"]
#hosts: ["www.musha.co.jp"]
#hosts: ["www.teijin.co.jp", "www.teijin.com"]
##hosts: ["www.yamaha.com"]
#hosts: ["yemen.jp"]
#hosts: ["okinawa2go.jp", "en.okinawa2go.jp"]
#hosts: ["blog.tokyosharehouse.com"]
#hosts: ["www.nesic.co.jp"]
#hosts: ["www.bostonscientific.com"]
#hosts: ["cwaj.org"]
#hosts: ["www.saa-safe.org"]
##hosts: ["corporate.evonik.jp"]
#hosts: ["www.spielzeug-welten-museum-basel.ch"]
#hosts: ["www.sekisuimedical.jp"]
##hosts: ["ww1.issa.int"]
##hosts: ["www.hijapan.info"]
#hosts: ["www.praemiumimperiale.org"]
#hosts: ["www.ntt.co.jp"]
#hosts: ["www.inter-bee.com"]
#hosts: ["yokohama.mylifehouse.com"]
#hosts: ["www.cstf.kyushu-u.ac.jp"]
#hosts: ["www.roots-web.jp"]
#hosts: ["kiua.kyotoiu.ac.jp"]
#hosts: ["www.sfc.itc.keio.ac.jp"]
#hosts: ["www.jbic.go.jp"]
#hosts: ["www.wien.info"]
#hosts: ["www.bewith.jp"]
#hosts: ["www.hataoka.jp"]

task: [
    #    "concat",
    #    "preprocessing",
    #    "align-document",
    #    "align-paragraph",
    #    "align-sentence",
    "filtering",
    "finish",
]

crawler: heritrix

ftfy: true

cleanHTML: true

boilerpipeCleaning: false

#pdf-converter: "pdf-extract"

parser: bs4

neologdn: true

langId: cld2

documentAligner: URL

paragraphAligner: STRAND

sentenceAligner: HUNALIGN
#sentenceAligner: LASER

#filter: BICLEANER
filter: ZIPPORAH

strandThreshold: 0.1
strandDpThreshold: 0.3

hunalignDic: /data/bitextor/model/hunalign/en-ja/hunalign.en-ja.dic
hunalignThreshold: 0.0

laser_model_dir: /root/LASER/models
laser_encoder: /root/LASER/models/bilstm.93langs.2018-12-26.pt
laser_bpe_codes: /root/LASER/models/93langs.fcodes
laser_threshold: 1.1
laser_enc_gpu: false
laser_knn_gpu: false

bicleanerConfig: /data/bitextor/model/bicleaner/en-ja/bicleaner.en-ja.yaml
bicleanerThreshold: 0.4

zipporahDir: "/data/bitextor/model/zipporah/en-ja"
zipporahConfig: "/data/bitextor/model/zipporah/en-ja/config"
zipporahModel: "/data/bitextor/model/zipporah/en-ja/en-ja.model"
zipporahDic1: "/data/bitextor/model/zipporah/en-ja/dict.en-ja"
zipporahDic2: "/data/bitextor/model/zipporah/en-ja/dict.ja-en"
zipporahVocab1: "/data/bitextor/model/zipporah/en-ja/vocab.en"
zipporahVocab2: "/data/bitextor/model/zipporah/en-ja/vocab.ja"
zipporahLM1: "/data/bitextor/model/zipporah/en-ja/lm.en"
zipporahLM2: "/data/bitextor/model/zipporah/en-ja/lm.ja"
zipporahThreshold: 0.5

bifixer: false

elrc: false

miniclean: false
minicleanLID: "fastText: /root/fastText/model/lid.176.bin"

tmx: true

deduped: true
