temp: /tmp

dataDir: /data

crawlTimeLimit: "86400"

heritrixPaths:
  - /heritrix/0
  - /heritrix/1
  - /heritrix/2
heritrixUrls:
  - https://localhost:8440
  - https://localhost:8441
  - https://localhost:8442
heritrixUser: admin:admin
heritrixContactUs: https://paracrawl.eu/ 
heritrixBeans: ./crawler-beans.cxml

seeds: ["http://ahatoro.com/", "http://okinawa2go.jp/", "http://en.okinawa2go.jp/"]
