temp: /tmp

dataDir: /data

crawlTimeLimit: "86400"

heritrixPath: /data/heritrix
heritrixUrl: https://localhost:8443
heritrixUser: admin:admin
heritrixContactUs: https://paracrawl.eu/ 
heritrixBeans: ./crawler-beans.cxml

seeds: ["http://ahatoro.com/", "http://okinawa2go.jp/", "http://en.okinawa2go.jp/"]
